### ISSUE TITLE
Some seeders doesn't work

### ISSUE THREAD

**Issue by fmendozaro** [threeiscompany-exercise/atm-adlister#23]
Check your seeder files, they fail

adlister_cat_migration.sql
adlister_db_ads_seeder.sql

Is there a particular order to run them?

Specify that in the name, example:

00_migration.sql
01_first_seeder.sql
02_second... and so on

**Comment by fmendozaro** [comment]
Can somebody assign this issue @mcoindreau @tlh5867 @arturva24  ?

**Comment by tlh5867** [comment]
Mari is working on it

**Comment by arturva24** [comment]
the cat migration was not supposed to be updated to git hub.  Something she was working on then scrapped it.  Will update the current seeders

**Comment by mcoindreau** [comment]
migration and seeders files corrected and file names changed in order of precedence

**Comment by fmendozaro** [comment]
If 01-adlister-table-migration.sql is the first one i think it's missing a create db if exists statement.
